name: tag

on:
  workflow_call:

jobs:
  tag:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    outputs:
      new_version: ${{ steps.version.outputs.tag }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          submodules: true

      - name: Detect and tag new version
        uses: salsify/action-detect-and-tag-new-version@v2
        id: version
        with:
          create-tag: true
          tag-template: "{VERSION}"
          version-command: |
            cat VERSION
