name: releaser

on:
  push:
    branches: [main]

jobs:
  releaser:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          submodules: true

      - name: Detect and tag new version
        uses: salsify/action-detect-and-tag-new-version@v2
        with:
          create-tag: true
          tag-template: "{VERSION}"
          token: ${{ secrets.GITHUB_TOKEN }}
          version-command: |
            cat VERSION

      - name: Setup odin
        uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release: false

      - name: Build release
        run: ./build_release.sh
