name: releaser

on:
  push:
    branches: [main]

jobs:
  tag:
    uses: ./.github/actions/tag.yml

  changelog:
    uses: ./.github/actions/changelog.yml
    needs: [tag]
    if: needs.tag.outputs.new_version


  build:
    uses: ./.github/actions/build.yml
    needs: [tag, changelog]
    if: needs.tag.outputs.new_version
    with:
      NAME: ox
